### login
POST {{PUBLIC_API_URL}}/auth/login
Content-Type: application/json

{
  "username": "user1",
  "password": "jadal123"
}

### dailyReports
GET {{PUBLIC_API_URL}}/daily-reports
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.accessToken}}
x-local-id: {{login.response.body.$.data.locals.0.localId}}

### availableDailyReports
GET {{PUBLIC_API_URL}}/daily-reports/available-cash-registers
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.accessToken}}
x-local-id: {{login.response.body.$.data.locals.0.localId}}
