### login
POST {{PUBLIC_API_URL}}/auth/login
Content-Type: application/json

{
  "username": "user1",
  "password": "jadal123"
}

### detailBoxes
GET {{PUBLIC_API_URL}}/cash-registers
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.accessToken}}
x-local-id: {{login.response.body.$.data.locals.0.localId}}

### detailBox
GET {{PUBLIC_API_URL}}/cash-registers/liquidation/{{detailBoxes.response.body.$.data.0.cashRegisterId}}
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.accessToken}}
x-local-id: {{login.response.body.$.data.locals.0.localId}}

